language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 936cc6362209303a38421c0c4f4053d911a42268
 local_dir: dist
 on:
   branch: master