language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 7f1fdd84ed9933a548e5b99fb9959a75abbb4f79
 local_dir: dist
 on:
   branch: master