language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 56f3005c3390052c3bb4537293cffdab7aaddcf8
 local_dir: dist
 on:
   branch: master