language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 5a1f254c5be2c5337024a11cb20a8f062fdcdc1e
 local_dir: dist
 on:
   branch: master